name: Scheduled Python Package Installation and Script Execution

on:
  schedule:
    - cron: '0 9 * * *'  # Schedule the workflow to run at 9 AM UTC time every day

  workflow_dispatch:  # Allow the workflow to be run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute Script
      run: echo "Hello World"