name: Scheduled Python Package Installation and Script Execution

on:
  schedule:
    - cron: '0 9 * * *'  # Schedule the workflow to run at 9 AM UTC time every day

  workflow_dispatch:  # Allow the workflow to be run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean Up Environment
      run: |
        pip uninstall aiohttp
        # Add similar steps for other dependencies if needed

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp==3.7.4  # Specify the compatible aiohttp version
        pip install beautifulsoup4 requests openai
        # Add more packages as needed

    - name: Execute Python Script
      run: python today_news.py