name: Scheduled Python Package Installation and Script Execution

on:
  schedule:
    - cron: '1 0 * * *'  # Schedule the workflow to run at 9 AM every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute Script
      run: echo "Hello World"